### ISSUE TITLE
ToDo [Read this before you post something!]

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/Online-Privacy-Test-Resource-List#3]
Please not ask or open any ticket which is on the this todo list - to not waste time or to possible confuse people. Thanks. :+1: 

**ToDo:**
- Add github-gh page (front-page)
- Add (maybe) gitter chat 
- Add an page index to easier navigate to the specific sections 
- Table view?
- Mention [HTTPS Client Identification Using SSL/TLS](https://www.muni.cz/research/publications/1299983?lang=en)
- Mention document fingerprinting (basically metadata), same goes to pictures, ... 
- Add small overview what the page exactly do
- ~Add a warning that all of these pages mostly require JavaScript which must be e.g allowed via NoScript/umatrix.~
- Integrate googles fingerprinting ? -> [source](http://www.scottsmitelli.com/articles/youtube-audio-content-id) + mention if it's impossible to [prevent](http://www.w3.org/wiki/images/7/7d/Is_preventing_browser_fingerprinting_a_lost_cause.pdf).
- Some pages itself may collecting a online/offline database?! Research + proof needed. But it would make sense if they sell the collected data to Google, Amazon and others ... 
- Mark deprecated (because fixed by OS/Browser) test with an icon? It would help to identify if that is already fixed or not to avoid to submit unnecessary data and of course it would costs your time ... 
- ....

**Comment by CHEF-KOCH** [comment]
I may consider if some of my public projects are _stable_ that I maybe mention it over [hackernews](https://news.ycombinator.com/) to get some hype. :laughing: :rocket:

**Comment by Gitoffthelawn** [comment]
I think the feedback you might receive could be useful.  People helping people.

**Comment by Atavic** [comment]
Why not? Pants project about Firefox user.js has a good feedback:
http://www.ghacks.net/2016/07/03/comprehensive-firefox-user-js/

**Comment by CHEF-KOCH** [comment]
I not understand what you want to say with this. I will not add other projects, the goal is to use this project as a global base, what people want to do with it is up to them, they can integrate it in their addons/extensions like I try with my own FF addon which I'm still working on. If I add more stuff I will break this.

**Comment by Atavic** [comment]
I just pointed at a blog that could be interested for an article about your Windows Registry Tweaks (Win 7 - Win 10).

The specific Pants project isn't so interesting... There are too many user.js around and they all appear too permissive to me.

**Comment by Atavic** [comment]
http://www.uniquemachine.org/ on Github: https://github.com/Song-Li/cross_browser

**Comment by CHEF-KOCH** [comment]
After over 30+ hours collecting research - I almost got a full list of all API's what can reveal or possible compromise your identify. 

However, after I found everything I'm unsure if it's wise to publish it or if I suggest to block it. 

* It almost break the entire web experience
* Instead of blocking I prefer browser based implementation fixes for this 
* There is no pull or issue ticket on entire internet which handle this topic or to address it because it's complex and the negative consequences are huge, even if you would build an system which allows 'click-to-allow' methods like ScriptSafe it's for an normal user impossible to decide what he should block or not. Or he might give up because you spent entire day clicking on stuff (like I did last 8 months for tests). 
* An global lists might can help to solve this to make an black- and/or whitelist. The problem here is that some pages implementing own homebrew apis which means a lists would't help in this case and it ends up with exclusions and/or clicking.

I'm not sure if that is really necessary if it comes to 'security', most people already know that I always want proof and there is literally no proof which tells that one or two of such API's expose your entire identify. They of course can collect meta-data but that doesn't necessarily mean that you're compromised. And I can#t say this often enough, none or almost all pages requiring JavaScript which means if you disallow JavaScript by default via NoScript or ScriptSafe or other tools, then this also not plays any role - moreover there should be systems which detect such things when you allowed JavaScript and offering you to disallow or allow certain things, which again leads in the clicking problem. 

What I don't get is that there is besides my project (which I sadly currently maintain alone) no growd directly implemented in popular solutions to submit such things automatically or via opt-in toggle. The web is simply huge and the more people helping the chance is less that you run into troubles, remember four eyes are better than two. 

I'm also not sure how to address this or what I should do at this point because I could submit and discuss this internally with the Chromium team but I already know the answer, same goes to Tor. 

The last thing is that I'm not really happy with the current situation, because you need at least 3 or more addons to harden your browser, instead there should be one which covers it all but for whatever reason it seems to complicated for normal people to use - I'm pretty sure it's possible to merge uMatrix/NoScript and uBlock into one extension with effort but again it always ends up with clicking and wasted lifetime because there is no database for it which is totally not understandable (for me). There is Easylist and 100 other lists but not one which does merge it all because everyone seems to cook his own soup (I'm btw not talking about cosmetic filters aka own needs). 

If anyone want to contact me on this to make useful suggestions or want to help me fix this state I would totally appreciate this. 

CK

**Comment by Atavic** [comment]
You can start sharing in parts. How many APIs have you listed? If you start let's say with some Google API, it has specific URLs and a specific title for the .js

This repo and your recent [ASN](https://github.com/CHEF-KOCH/ASN-blocking) intrigue me.

**Comment by CHEF-KOCH** [comment]
Personally I not use any adblocking addon anymore because [Pi-hole](https://pi-hole.net/) is the new king of the hill. 

Well my ASN list and the mentioned API's have very less in common since I'm talking about if it wise to really block them. Most so called 'spying' API's like battery does at the end no harm to anyone, except that they might help on e.g. mobile devices. Such API's aren't designed to spy on you - but in internet times, one spread something and everyone re-spell it, ...

I remember the WebRTC discussion, when people recommend to totally disable it, WebRTC by design is like VOIP not a protocol itself, it's collection of bunch protocols like UDP to provide new interfaces which then can be called by the Browser (similar like .avi which is just a container and not a format by itself). 

I'm not sure if I in the future only provide simply filter lists like fanboy or if I try to improve the ASN thing which might can be integrated directly into the firewall but I'm not really a fan of it, both are time consuming.

**Comment by Atavic** [comment]
If the net development was correct, I should be able to still see a minimal, clean page: something like a text-only web, with 3rd party content - as CDN - stripped away.
But that's impossible, as some requirements like JS are often present in most sites.

As an example: github recently forced the users to the latest versions of most popular browsers. That's clearly a step toward a deeper integration with 3rd parties.

What has changed in github for this push to the newest versions? I assume nothing, as what has changed are the multiprocess browsers. That means more pings to the big actors: I point at CDNs like akamai and the few others that are present in almost all sites.

**Comment by CHEF-KOCH** [comment]
Well I totally get the point but the problem is at some point:
* Forcing user to use latest browser is (as some point) not a bad thing [security reasons]
* It might allows new API's which are more secure which aren't supported by older browsers 

Well, a lot of words but I want to keep it short. I see projects like ghacks user js and others, and there is so many BS, cause no one ever give really proof that disabling all really 'helps' or that they are abused. 

So you think replacing Google API with Mozilla's makes any difference? Who makes you think they not sell it? It's matter of trust, also google was never hacked. Just because there was literally one NSA page which shows they grabbed data from the big ones, doesn't mean that there not collecting data from all others too. I'm not here to defend google or something, I have my own doubts, but it's more complicated than disabling stuff and think you're more secure - you lower the risk but not fix browser vulnerables. 

As for Github, they recently changed their server structure from an over 10 years old system to a new one, I guess that seems to be the new reason, along with [other features](https://github.com/blog). 

I'm not sure where all this ends, at the end we trying to find ways to fix protocol issue which aren't fixable, cause this would break protocols. Speaking of that, Google, Facebook, MS and others are building such new web protocols, like [QUIC](https://techcrunch.com/2015/04/18/google-wants-to-speed-up-the-web-with-its-quic-protocol/), [HTTP2](https://http2.github.io) and others. And there all open source, so I not really understand the general distrust without proof, because without them the web would in fact less secure and fast. 

As you said CDN's are in general a problem, because in most cases you can't simply disable it, just locally emulate it via extensions, but you might run into security risk anyway because you use outdated or deprecated methods and on the other side it's a trust thing when you go the 'normal' way and allow them. I think we need a lot of research on that to really come to an conclusion. Of course there some which are might really designed to just track you but from what I know, most aren't and the websites using another services to track you, because it's more comfortable to use external services [cause laziness] which also ends up with possible risks because each external resources you use in your website might ends up with less control over the delivered content aka infection [infect one -> infects all].

**Comment by Atavic** [comment]
I'm more interested at router hardening than fiddling with firefox or palemoon settings at this point. Recent firefox starts some service instances - like chrome - and that can't be blocked.

Like the windows 10 charade, it's time to improve the router OS.

**Comment by CHEF-KOCH** [comment]
Well you could use PI-Hole when you're router firmware (OS) doesn't support a native interface for 'WebBugs' aka tracking. Of course you could use after mark firmware like OpenWRT but again, when you use a secured connection your router can't look into the packages, which is a huge problem, since malicious behaviour isn't visible or only with huge effort. 

Theoretically if you want a secure router you need to disallow HTTPS and monitor the traffic which goes in via Whireshark or Burp Suite, cause at some point decrypting the HTPPS content isn't an option. But uargh, of course HTTP itself is also not an option. So here we go again. 

But I guess a router which supports OpenWRT + PI-Hole already can block a lot with less effort.

**Comment by Atavic** [comment]
Yes, I'm looking at an ASUS model suitable for an aftermarket OS installation.

HTTPS? I had this idea for months: What if this push to secure connections is just another tracking effort? OCSP servers are pinged without any shielding by default.

**Comment by CHEF-KOCH** [comment]
I would't trust ASUS, LinkSys or Netgear (just saying) cause there all on the 'blacklist'. Better go with AVM which is a German product and their firmware is open source, there is also an aftermark firmware available to flash and modify (well to play with called freetz). Well it's up to you. 

About OCSP? I would't mess with that unless you show me and others that this is a threat. OCSP is encoded in ASN.1 which means HTTP is used for the request. Which means you can inspect it very easily without much effort. If you distrust one OCSP checking mechanism due privacy concerns you can simply disallow the certificate on OS level, well on Router level there is no need for that cause it never passes the router to other plugged-in hardware unless it's requested. And if you're not a sever admin you better control this via browser/OS. Maybe this could be a feature request for PI-Hole project cause it does support OpenSSL, which could allow us to 'grep' and block e.g. certs like digitalocean. 

It looks basically like this:

```
OCSP response:
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: 4C58CB25F0414F52F428C881439BA6A8A0E692E5
    Produced At: May  9 08:45:00 2014 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: B8A299F09D061DD5C1588F76CC89FF57092B94DD
      Issuer Key Hash: 4C58CB25F0414F52F428C881439BA6A8A0E692E5
      Serial Number: 0161FF00CCBFF6C07D2D3BB4D8340A23
    Cert Status: good
    This Update: May  9 08:45:00 2014 GMT
    Next Update: May 16 09:00:00 2014 GMT
```

So on the PI-Hole/Router level the fingerprint could be simply disallowed.

**Comment by Atavic** [comment]
ASUS Router BIOS: Advanced tab --> Trusted Computing

If I enable Security Device Support and save preferences, then TPM would appear in Device Manager.

**Comment by CHEF-KOCH** [comment]
Router not having a 'Bios' they have a firmware. Well, about [TPM modules](https://github.com/CHEF-KOCH/NSABlocklist/issues/5). There  more security concern then using OCSP. 

I'm not really sure what you want to tell me with this, cause TPM and OCSP are both different topics and OCSP is trustable while TPM can be an ultimative backdoor. No german or high security router I know use such chips on a router for a reason, so I really have my doubts. Besides this, as said there listen on the [blacklist](https://qz.com/1008273/complete-list-of-wifi-routers-included-in-wikileaks-cherryblossom-release-possibly-vulnerable-to-cia-hacking-tools/) together with other chips.

**Comment by Atavic** [comment]
Will check AVM.

**Comment by CHEF-KOCH** [comment]
[AVM](https://en.avm.de) is only manufacture together with some special designed high security router [which you can't pay -> expensive] which are imho trustable).

A friend also works for them, if there are any concerns or question, I could bring him up over here to answer it. But it's well documented and the [firmware is public on their ftps visible](https://download.avm.de/fritz.box/).
