### ISSUE TITLE
You're back!

### ISSUE THREAD

**Issue by Gitoffthelawn** [CHEF-KOCH/Online-Privacy-Test-Resource-List#4]
No great place to post this... so...

Glad to have you back!  What happened?

**Comment by CHEF-KOCH** [comment]
Hey, thanks. The full story can be found on ghacks or on my [Gists](https://gist.github.com/CHEF-KOCH/9ca1e2acc46276992ebda97a484d8635).

**Comment by Gitoffthelawn** [comment]
So weird how they didn't notify you.  Happy your account is in good standing again.  I always value your input and feedback.
